### ISSUE TITLE
SyntaxError: Unexpected token export in index.js

### ISSUE THREAD

**Issue by jennycai0807** [wpbdry/google-slides#1]
Thanks for your API, I'd like to use it but got some errors at node_modules/google-slides/index.js:1
The error is:
(function (exports, require, module, __filename, __dirname) { export { API, TextReplacement } from './api.js'

SyntaxError: Unexpected token export
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

**Comment by wpbdry** [comment]
Hi @jennycai0807 

Please make sure you are using the latest version of nodejs:
```
nvm install node
nvm use node
node -v
```
The output from the last line must be `13.11.0` or greater, otherwise this package will not work for you.

You may also need to add `"type": "module"` to your `package.json` file.

I am closing this issue for now. If neither of these steps fixes your problem, please create a new issue, and include your node version, the exact code you are running, and the error you are getting.

Thanks! :)
